#!/usr/bin/perl -w

use POSIX;

my $db = "db.fastq";
my $infile = "input.fastq";
my $outfile = "output.fastq";
my $seqs_per_file = 10000;

$nseqs = `./fastq_count.pl $infile`;
chomp $nseqs;

$nfiles = 1 + int($nseqs / $seqs_per_file);

print "# $nseqs $nfiles $seqs_per_file\n";

my $inputlist;
my $outputlist;

for (my $i = 0; $i < $nfiles; $i++) {
	$inputlist .= "$infile.$i ";
	$outputlist .= "$outfile.$i ";
}

print "OPTIONS=-tags 1 -rtype abi -score 30 -seeds 5 -output ssaha2\n";

print "$inputlist: $infile fastq_split.pl\n";
print "\tLOCAL ./fastq_split.pl $infile $seqs_per_file\n\n";

for (my $i = 0; $i < $nfiles; $i++){
	print "$outfile.$i: $infile.$i $db ssaha2\n";
	print "\t./ssaha2 \$OPTIONS $db $infile.$i > $outfile.$i\n\n";
}

print "$outfile: $outputlist\n";
print "\tLOCAL cat $outputlist > $outfile\n\n";
