#!/usr/bin/perl -w

use POSIX;

my $db = "ref.db";
my $splits = 25;
my $infile = "input.fastq";
my $outfile = "output.fastq";

my $inputlist;
my $outputlist;

for (my $i = 0; $i < $splits; $i++) {
	$inputlist .= "input.$i ";
	$outputlist .= "output.$i ";
}

print "OPTIONS=-tags 1 -rtype abi -score 30 -seeds 5 -output ssaha2\n";

print "$inputlist: $infile split.pl\n";
print "\tLOCAL ./split.pl input.fastq $splits\n\n";

for (my $n = 0; $n < $splits; $n++){
	print "output.$n: input.$n $db ssaha2\n";
	print "\t./ssaha2 \$OPTIONS $db input.$n > output.$n\n\n";
}

print "$outfile: combine.pl $outputlist\n";
print "\tLOCAL ./combine.pl output.fastq $splits\n";
